[workspace]
members = [
    "ic-agent/",
    "ic-identity-hsm/",
    "ic-types/",
    "ic-utils/",
    "icx/",
    "icx-proxy/",
    "ref-tests/",
]

[patch.crates-io]
ic-types = { path = "./ic-types", version = "0.2", features = [ "serde" ] }
