[workspace]
members = [
    "ic-agent",
    "ic-agent-ifaces",
    "ic-asset",
    "icx-cert",
    "ic-identity-hsm",
    "ic-utils",
    "icx",
    "icx-asset",
    "icx-proxy",
    "ref-tests",
    "zzz-release",
]
