name: ic-ref

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ linux-0-9 ]
        include:
          - build: linux-0-9
            ghc: '8.8.3'
            spec: 'release-0.10'
            os: ubuntu-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/checkout@v2
        with:
          repository: 'dfinity-lab/ic-ref'
          # Personal Read-only Access Token created by hans.larsen@dfinity.org
          token: ${{ secrets.IC_REF_TOKEN }}
          path: ic-ref
          ref: ${{ matrix.spec }}

      - name: Cache /nix/store
        uses: actions/cache@v1
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-store

      - uses: cachix/install-nix-action@v10
        with:
          skip_adding_nixpkgs_channel: false

      - name: Build ic-ref
        run: |
          nix-build ic-ref -A ic-ref
          echo "::add-path::$(readlink result)/bin"

      - name: Build universal-canister
        run: |
          nix-build ic-ref -A universal-canister
          echo "::set-env name=IC_UNIVERSAL_CANISTER_PATH::$(readlink result)/universal_canister.wasm"

      - name: Run Tests
        run: |
          set -ex
          ic-ref --pick-port --write-port-to $HOME/ic_ref_port &
          sleep 1
          export IC_REF_PORT=$(cat $HOME/ic_ref_port)
          echo "Using universal canister at $IC_UNIVERSAL_CANISTER_PATH"
          cd main/ref-tests
          cargo test --all-features -- --ignored
          killall ic-ref
        env:
          RUST_BACKTRACE: 1

      - name: Run Doc Tests
        run: |
          set -ex
          $HOME/bin/ic-ref --pick-port --write-port-to $HOME/ic_ref_port &
          sleep 1
          export IC_REF_PORT=$(cat $HOME/ic_ref_port)
          cd main
          cargo test --all-features --doc -- --ignored
          killall ic-ref
        env:
          RUST_BACKTRACE: 1
